sudo: true

env:
- PS_FORMAT=user,pid,ppid,nlwp,%mem,args

before_install:
- sudo aptitude update -Z
- sudo aptitude install nginx -Z --assume-yes
- curlw () { curl --connect-timeout 1 $@ | w3m -dump -T text/html }
- ping1 () { ping -c 1 $@ }
- ipeth0=$(ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//' | head --lines=1)


script:
- service nginx status
- curlw http://localhost
- ping -c 1 $(curl http://icanhazip.com)
- curlw http://$(curl http://icanhazip.com)
- ping1 $ipeth0
- curlw $ipeth0


after_script:
- man nginx
- dpkg --listfiles nginx
- dpkg --listfiles nginx-common
- dpkg --listfiles nginx-core
- ls --color --recursive /etc/nginx
- cat /etc/nginx/nginx.conf
- cat /etc/nginx/sites-available/default
- grep 'server_name.*;$' /etc/nginx/sites-available/*
- cat /etc/default/nginx
- ls --color /usr/share/nginx/html
- w3m -dump /usr/share/nginx/html/index.html
- w3m -dump /usr/share/nginx/html/50x.html
- ps -C nginx
- ls -A --color /var/www
