sudo: true


before_install:
- sudo aptitude update -Z
- sudo aptitude install nginx -Z --assume-yes
- sudo aptitude install links -Z --assume-yes


script:
- service nginx status
- links -dump http://localhost:80


after_script:
- man nginx
- ls -A --color /var/www
